receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
          - http://*
          - https://*
exporters:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  logging:
    loglevel: debug
    sampling_initial: 10
    sampling_thereafter: 2
extensions:
  health_check:
  zpages:
processors:
  batch:
  queued_retry:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger, logging]
    # metrics:
    #   receivers: [otlp]
    #   exporters: [prometheus]
    #   processors: [batch, queued_retry]
