{
 "title": "Example",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency per operation (p99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(operation_summary{quantile='0.99'}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "All  Operations Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(operation_histogram_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "getItems success / error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(operation_success{name=\"getItems\"}[5m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(operation_error{name=\"getItems\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "getItemsRoute Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(operation_histogram_bucket{name=\"getItemsRoute\"}[$__interval])",
     "legendFormat": "{{le}}"
    },
    {}
   ]
  }
 ]
}